<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Data\second.new" />
    <None Remove="Data\second.old" />
    <None Remove="Data\simple.new" />
    <None Remove="Data\simple.old" />
    <EmbeddedResource Include="Data\Second\new" />
    <EmbeddedResource Include="Data\Second\old" />
    <EmbeddedResource Include="Data\First\new" />
    <EmbeddedResource Include="Data\First\old" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="Spectre.IO.Testing" />
    <PackageReference Include="Spectre.Verify.Extensions" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="..\Verify.Terminal\Verify.Terminal.csproj" />
  </ItemGroup>
</Project>
